language: python

python:
  - 2.7

env:
  global:
    - PATH: "/opt/texbin:/usr/local/texlive/2014/bin/x86_64-linux:$PATH"
    - secure: BqTquD24xLwjcQ/zgFx9yApUvDMrn5tncC8sEe0J41ozQiGIqIz78SRHda8G89gXuQSrS33gJeZJe2mcsQArfw7rbn034ee9Tcn3S+OFNFNWPN5tG9+OCnrSRRGD48NRiBpdkOYG5gWLXvOolCm9PBrxZik0QPFnOJ06y2WwfaM=

install:
  - cd ..
  - wget -c http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - mkdir texlive
  - tar -zxf install-tl-unx.tar.gz -C ./texlive --strip-components=1
  - cd texlive
  - sudo ./install-tl -profile $TRAVIS_BUILD_DIR/.travis/texlive.profile
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --self
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --all
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/texhash
  - cd $TRAVIS_BUILD_DIR
  - pip install pygments

script:
  - make
  - ".travis/deploy.sh"

notifications:
  slack:
    secure: DZ6bF+lgkE5b/YgAmp5e2+D3QdUkl/O9BatmRm/WUL0g/kV7khlvY9W9PDjGTQNgxJc0B472xpGx1yBe834vS/wK9+XGnoERqjpbX4qcMP4uUHzJk7FpMq1bJNTXZeE5NnfgX4G6uliFEixvB66ljtdLLsNLYpKYCX0WR68PHHc=
  on_failure: always
  on_success: change
