install:
    - sudo apt-get install texlive-full chktex
    - sudo tlmgr update --self --all --reinstall-forcibly-removed

script:
    - pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error -shell-escape main.tex
