language: python

python:
  - 2.7

env:
  global:
    - PATH: "/opt/texbin:/usr/local/texlive/2014/bin/x86_64-linux:$PATH"
    - secure: BqTquD24xLwjcQ/zgFx9yApUvDMrn5tncC8sEe0J41ozQiGIqIz78SRHda8G89gXuQSrS33gJeZJe2mcsQArfw7rbn034ee9Tcn3S+OFNFNWPN5tG9+OCnrSRRGD48NRiBpdkOYG5gWLXvOolCm9PBrxZik0QPFnOJ06y2WwfaM=

install:
  - cd ..
  - wget -c http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - mkdir texlive
  - tar -zxf install-tl-unx.tar.gz -C ./texlive --strip-components=1
  - cd texlive
  - sudo ./install-tl -profile $TRAVIS_BUILD_DIR/.travis/texlive.profile
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --self
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --all
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/texhash
  - cd $TRAVIS_BUILD_DIR
  - pip install pygments

script:
  - make
  - make protocols
  - ".travis/deploy.sh"

notifications:
  slack:
    on_failure: always
    on_success: change
    secure: VBTfkdECN8/8UMuoU/e/T3QZIQLjevpzL9JhYDCRjOaey2oby2LdWptJaKzczsR0y2rSHQga5LG/Zg96bZgaW7cK1abgxuxYge/DQtq3Wvln7lW0m8aJZaOk/fHhFi5I/daYTN0bJMo/pmUSxlk2PMK6AhuChVdIMBk5sQxlg2s=
