install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex

script:
    - pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error -shell-escape main.tex
